# Generated by Django 4.1.2 on 2022-10-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, unique=True)),
                ('last_name', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=12)),
                ('user_email', models.EmailField(max_length=70, unique=True)),
                ('user_mobile', models.IntegerField()),
            ],
        ),
    ]
