# Generated by Django 4.1.2 on 2022-10-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0002_alter_barber_barber_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_mobile',
            field=models.IntegerField(),
        ),
    ]
