# Generated by Django 4.1.2 on 2022-10-05 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0004_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
